import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

async function generateUrl () {
	const fetchPromise = () => new Promise((resolve, reject) => {
		fetch('http://localhost:3000/api/v1/veronica/generateloginurl', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
				'Authorization': `Basic ${process.env.NEXT_PUBLIC_AUTH_ID}:${process.env.NEXT_PUBLIC_AUTH_SECRET}`
			},
			body: JSON.stringify({
				uriName: "coglogin",
				responseType: "code",
				state: ""
			})
		}).then(res => resolve(res)).catch(error=>{ reject(error) })
	});

	const {result, response} = await fetchPromise().then(res=>res.json()).catch(error=>{ return error });
	
	if (result) {
		window.location.href = response.url;
	}
}

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h1 className={styles.title}>Website A</h1>
				<div className={styles.grid}>
					<div className={styles.card} onClick={()=>generateUrl()}>
						<h2>Generate Login Url</h2>
						<p>Find in-depth information about Next.js features and API.</p>
					</div>
				</div>
			</main>
		</div>
	);
}
